# config.py

TELEGRAM_TOKEN = '7426543281:AAHu4Qf_KT6sGBaqUJU5ccFKZroHKrVc9R0'
CHAT_ID = '1385370555'
SELECTED_SYMBOLS = [
    'RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'HDFC.NS', 'ICICIBANK.NS', 
    'KOTAKBANK.NS', 'SBIN.NS', 'LT.NS', 'ITC.NS', 'AXISBANK.NS', 'HINDUNILVR.NS', 
    'BAJFINANCE.NS', 'ASIANPAINT.NS', 'MARUTI.NS', 'BHARTIARTL.NS', 'TATASTEEL.NS', 
    'M&M.NS', 'SUNPHARMA.NS', 'WIPRO.NS', 'ULTRACEMCO.NS', 'POWERGRID.NS', 
    'HCLTECH.NS', 'NESTLEIND.NS', 'BAJAJFINSV.NS', 'JSWSTEEL.NS', 'DRREDDY.NS', 
    'ADANIPORTS.NS', 'TITAN.NS', 'GRASIM.NS', 'INDUSINDBK.NS', 'HINDALCO.NS', 
    'HEROMOTOCO.NS', 'BRITANNIA.NS', 'DIVISLAB.NS', 'ONGC.NS', 'BPCL.NS', 
    'TECHM.NS', 'COALINDIA.NS', 'SBILIFE.NS', 'SHREECEM.NS', 'EICHERMOT.NS', 
    'IOC.NS', 'ADANIGREEN.NS', 'ADANIENT.NS', 'GAIL.NS', 'HDFCLIFE.NS', 
    'VEDL.NS', 'ADANITRANS.NS', 'UPL.NS', 'DMART.NS', 'NTPC.NS'
]  # Replace with your chosen NSE symbols
